# Generated by Django 5.2.6 on 2025-09-22 12:33

import signature_pad.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.TextField(verbose_name='Описание')),
                ('generated_issue', models.TextField(blank=True, default='Неизвестно', null=True, verbose_name='Сгенерированная претензия')),
                ('signature', signature_pad.fields.SignaturePadField(blank=True, null=True)),
                ('generated_claim_pdf', models.FileField(blank=True, upload_to='data/generated_issue_pdf/', verbose_name='Cгенерированный pdf претензии')),
                ('user_agreement', models.FileField(blank=True, upload_to='data/generated_user_agreement/', verbose_name='Пользовательское соглашение')),
            ],
            options={
                'verbose_name': 'Претензия',
                'verbose_name_plural': 'Претензии',
            },
        ),
    ]
