# Generated by Django 5.2.6 on 2025-09-27 13:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawissue',
            name='generated_issue',
            field=ckeditor.fields.RichTextField(blank=True, default='Неизвестно', null=True, verbose_name='Сгенерированная претензия'),
        ),
    ]
