# Generated by Django 5.2.6 on 2025-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lawissue_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawissue',
            name='title',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
