# Generated by Django 5.2.6 on 2025-09-28 15:20

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lawissue_generated_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawissue',
            name='generated_claim_pdf',
            field=models.FileField(blank=True, upload_to=main.models.generated_issue_pdf_path, verbose_name='Cгенерированный pdf претензии'),
        ),
        migrations.AlterField(
            model_name='lawissue',
            name='user_agreement',
            field=models.FileField(blank=True, upload_to=main.models.user_agreement_pdf_path, verbose_name='Пользовательское соглашение'),
        ),
    ]
