# Generated by Django 5.2.6 on 2025-09-12 22:02

import signature_pad.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lawissue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawissue',
            name='Место для подписи',
            field=signature_pad.fields.SignaturePadField(blank=True, null=True),
        ),
    ]
