# Generated by Django 5.2.6 on 2025-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lawissue_generated_claim_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawissue',
            name='user_mail',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email пользователя'),
        ),
        migrations.AddField(
            model_name='lawissue',
            name='user_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон пользователя'),
        ),
    ]
