# Generated by Django 5.2.6 on 2025-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lawissue_user_mail_lawissue_user_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации')),
                ('charges_file', models.FileField(blank=True, null=True, upload_to='business/charges/', verbose_name='Файл начислений и оплат')),
                ('personal_data_claim_file', models.FileField(blank=True, null=True, upload_to='business/personal_data/', verbose_name='Претензия персональные данные')),
                ('snt_claim_file', models.FileField(blank=True, null=True, upload_to='business/snt/', verbose_name='Претензия СНТ')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='business/generated_pdf/', verbose_name='Сгенерированный PDF')),
                ('zip_archive', models.FileField(blank=True, null=True, upload_to='business/zips/', verbose_name='ZIP архив')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Бизнес-клиент',
                'verbose_name_plural': 'Бизнес-клиенты',
            },
        ),
    ]
