# Generated by Django 5.2.6 on 2025-09-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lawissue_место_для_подписи'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawissue',
            old_name='Место для подписи',
            new_name='signature',
        ),
    ]
