# Generated by Django 5.2.6 on 2025-09-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_место_для_подписи_lawissue_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawissue',
            name='model_predict',
            field=models.TextField(default='Неизвестно', verbose_name='Сгенерированная претензия'),
        ),
    ]
