# Generated by Django 5.2.6 on 2025-11-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_businessclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, verbose_name='Название рассылки')),
                ('total_debtors', models.IntegerField(default=0, verbose_name='Всего должников')),
                ('sms_sent', models.IntegerField(default=0, verbose_name='SMS отправлено')),
                ('emails_sent', models.IntegerField(default=0, verbose_name='Email отправлено')),
                ('status', models.CharField(default='processing', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='NotificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('snt_address', models.CharField(max_length=255, verbose_name='Адрес СНТ')),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма долга')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS отправлено')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email отправлено')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.notificationcampaign')),
            ],
            options={
                'verbose_name': 'Результат рассылки',
                'verbose_name_plural': 'Результаты рассылки',
            },
        ),
    ]
