# Generated by Django 5.2.6 on 2025-09-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lawissue_model_predict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawissue',
            old_name='model_predict',
            new_name='generated_issue',
        ),
    ]
