# Generated by Django 5.2.6 on 2025-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_model_predict_lawissue_generated_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawissue',
            name='generated_issue',
            field=models.TextField(blank=True, default='Неизвестно', null=True, verbose_name='Сгенерированная претензия'),
        ),
    ]
